"""Custom domain tools exposed to the LangGraph agents."""

from __future__ import annotations

from typing import Any

from .repository import IncidentRepository


class IncidentTools:
    def __init__(self, repository: IncidentRepository) -> None:
        self.repository = repository
    # fingerprint is a unique identifier for an incident, generated by hashing the normalized content of the incident report. 
    # It is used to check if an incident has already been logged in the system. helps prevent duplicate entries. 
    def incident_lookup(self, fingerprint: str) -> dict[str, Any] | None:
        """Return the previously logged incident with this normalized fingerprint."""
        return self.repository.find_by_fingerprint(fingerprint)

    def create_incident_record(self, incident: dict[str, Any]) -> int:
        """Create a newly submitted incident and initial history event."""
        return self.repository.create_incident(incident)

    def retrieve_history(self, incident_id: int) -> list[dict[str, Any]]:
        return self.repository.history(incident_id)

    def retrieve_evidence(self, incident_id: int) -> list[dict[str, Any]]:
        return self.repository.evidence_for(incident_id)

    def add_evidence(self, incident_id: int, source: str, content: str) -> None:
        """Attach a log extract, monitoring result, or other evidence to an incident."""
        self.repository.add_evidence(incident_id, source, content)

    def search_knowledge(self, query: str) -> list[dict[str, Any]]:
        return self.repository.search_knowledge(query)

    def search_similar_cases(self, system_name: str, incident_id: int) -> list[dict[str, Any]]:
        return self.repository.similar_cases(system_name, incident_id)

    def persist_report(self, incident_id: int, report: str) -> None:
        self.repository.save_report(incident_id, report)
